version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "radis-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15a64kld5rx7s"
s3_prefix = "radis-app"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = ["CalculateSpectrum=764662264940.dkr.ecr.us-east-2.amazonaws.com/radis-app"]
profile = "suzil"
confirm_changeset = true
