AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  RADIS application.

Globals:
  Function:
    Environment:
      Variables:
        HOME: /tmp
    MemorySize: 512
    ReservedConcurrentExecutions: 3
    Timeout: 30

  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: radis-app-frontend
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    # DeletionPolicy: Retain
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: FrontendBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref FrontendBucket
                - /*
      Bucket: !Ref FrontendBucket

  ServerlessRestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      MethodSettings:
        - ThrottlingBurstLimit: 10
          ThrottlingRateLimit: 1
          ResourcePath: "/*"

  CalculateSpectrum:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        CalculateSpectrum:
          Type: Api
          Properties:
            Path: /calculate_spectrum
            Method: post
            RestApiId: !Ref ServerlessRestApi

    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./calculate_spectrum
      DockerTag: python3.8-v1

Outputs:
  CalculateSpectrumApi:
    Description: "API Gateway endpoint URL for Prod stage for calculate spectrum function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/calculate_spectrum/"
  CalculateSpectrum:
    Description: "Calculate Spectrum Lambda Function ARN"
    Value: !GetAtt CalculateSpectrum.Arn
  CalculateSpectrumIamRole:
    Description: "Implicit IAM Role created for calculate spectrum function"
    Value: !GetAtt CalculateSpectrumRole.Arn
  WebsiteURL:
    Value: !GetAtt
      - FrontendBucket
      - WebsiteURL
    Description: URL for website hosted on S3
