name: GH

on:
  pull_request:
  push:
    # TODO
    branches: [master,switch-to-aws]
  release:
    branches: [master]
    types: [published]

jobs:
  cancel_previous_runs:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup AWS SAM
        uses: aws-actions/setup-sam@v0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        # TODO: Switch to roles for better security
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Pre-commit cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ matrix.python-version }}-${{ hashFiles('**/requirements/ci.txt') }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install the backend
        run: |
          pip install -U pip setuptools wheel
          make install

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: make lint

      # TODO
      # - name: Test
      #   run: |
      #     make backend &
      #     yarn start &
      #     make test

      - name: Deploy
        run: |
          sam build
          sam deploy
          export REACT_APP_CALCULATE_SPECTRUM_API=$(aws cloudformation describe-stacks --stack-name radis-app --query 'Stacks[0].Outputs[?OutputKey==`CalculateSpectrumApi`].OutputValue' --output text)
          echo $REACT_APP_CALCULATE_SPECTRUM_API
          CI=false yarn build
          aws s3 sync build/ s3://radis-app-frontend/
